---
services:

  rsyslog:
    #build:
    #  context: ./build
    #  dockerfile: Dockerfile
    image: ghcr.io/papamoose/docker-rsyslog-server:latest
    environment:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
    hostname: rsyslog
    container_name: rsyslog
    restart: unless-stopped
    volumes:
      - "./data:/rsyslog"
    ports:
      # The container runs as a normal user and uses port above 1024
      - 10514:10514
      - 10514:10514/udp
