---

services:
  rsyslog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - UID=${UID}
      - GID=${GID}
    environment:
    - TZ=America/Chicago
    user: "${UID}:${GID}"
    hostname: rsyslog
    container_name: rsyslog
    restart: unless-stopped
    volumes:
    - "./data:/rsyslog"
    ports:
    - 10514:10514
    - 10514:10514/udp
